FROM rust:latest

LABEL "com.github.actions.name"="Cargo"
LABEL "com.github.actions.description"="Execute cargo things"
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="Red"

LABEL "maintainer"="AlecAivazis <alec@aivazis.com>"

ENTRYPOINT ["cargo"]
